version: "3.7"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
    - 5432
    ports:
      - 5432:5432
    environment:
         - POSTGRES_PASSWORD=nimda
         - POSTGRES_USER=postgres
         - POSTGRES_DB=test_db
    restart: unless-stopped
  demo:
    image: demo:latest
    container_name: demo
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=qa
      - POSTGRES_PASSWORD=nimda
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test_db
    volumes:
      - demo-data:/logs
volumes:
  postgres-data:
  demo-data:
